### ISSUE TITLE
Incompatibility with CC 1.112.0

### ISSUE THREAD

**Issue by awesomebossdj7** [Lumina-CC/EmbeddedComputerMod#1]
**Issue:**
Using CC 1.112.0, if you right click on the embedded computer, its tries to open something and crashes the game

**Fabric Version(s):**
Latest (0.16.0)
Fabric API: Latest (0.92.2+1.20.1)

**Comment by awesomebossdj7** [comment]
let me send the log real quick

**Comment by awesomebossdj7** [comment]
main log that shows what happened + crash reason:
https://gist.github.com/awesomebossdj7/61845eececc0ddee5e09fc650cf0fed6

**Comment by awesomebossdj7** [comment]
oh also if you do this, and try to rejoin the world, it will be a ticking entity so you need something like neruina to fix it

**Comment by awesomebossdj7** [comment]
Also theres no current way to turn on the embedded computer

**Comment by WindClan** [comment]
Try using CC:Tweaked 0.111.0
the crash is due to 1.112.0 changing some constructors

**Comment by awesomebossdj7** [comment]
ah okay, i heard about that version breaking things and didnt even think to downgrade, ill still keep this open but rename it.

**Comment by WindClan** [comment]
oh my god the entire thing i used to add the API changed and the computer no longer connects to peripherals

**Comment by WindClan** [comment]
Fixed in https://github.com/Lumina-CC/EmbeddedComputerMod/commit/27d0870c704e777406820943e1aeaf2ca94f3c24

Im going to add more things before i push a release though

**Comment by awesomebossdj7** [comment]
alright thanks!
